// AUTO-GENERATED by scratchpad/gen_elements.mjs. Standard atomic weights;
// radioactive elements use their most stable isotope mass.
import type { ElementDef } from "../store/types.ts";

export const ELEMENTS: ElementDef[] = [
  {
    "z": 1,
    "symbol": "H",
    "name": "Hydrogen",
    "mass": 1.008,
    "category": "nonmetal",
    "period": 1,
    "group": 1,
    "xpos": 1,
    "ypos": 1,
    "oxidationStates": [
      -1,
      1
    ],
    "electronegativity": 2.2
  },
  {
    "z": 2,
    "symbol": "He",
    "name": "Helium",
    "mass": 4.0026,
    "category": "noble-gas",
    "period": 1,
    "group": 18,
    "xpos": 18,
    "ypos": 1,
    "oxidationStates": [
      0
    ],
    "electronegativity": null
  },
  {
    "z": 3,
    "symbol": "Li",
    "name": "Lithium",
    "mass": 6.94,
    "category": "alkali-metal",
    "period": 2,
    "group": 1,
    "xpos": 1,
    "ypos": 2,
    "oxidationStates": [
      1
    ],
    "electronegativity": 0.98
  },
  {
    "z": 4,
    "symbol": "Be",
    "name": "Beryllium",
    "mass": 9.0122,
    "category": "alkaline-earth",
    "period": 2,
    "group": 2,
    "xpos": 2,
    "ypos": 2,
    "oxidationStates": [
      2
    ],
    "electronegativity": 1.57
  },
  {
    "z": 5,
    "symbol": "B",
    "name": "Boron",
    "mass": 10.81,
    "category": "metalloid",
    "period": 2,
    "group": 13,
    "xpos": 13,
    "ypos": 2,
    "oxidationStates": [
      3
    ],
    "electronegativity": 2.04
  },
  {
    "z": 6,
    "symbol": "C",
    "name": "Carbon",
    "mass": 12.011,
    "category": "nonmetal",
    "period": 2,
    "group": 14,
    "xpos": 14,
    "ypos": 2,
    "oxidationStates": [
      -4,
      -3,
      -2,
      -1,
      1,
      2,
      3,
      4
    ],
    "electronegativity": 2.55
  },
  {
    "z": 7,
    "symbol": "N",
    "name": "Nitrogen",
    "mass": 14.007,
    "category": "nonmetal",
    "period": 2,
    "group": 15,
    "xpos": 15,
    "ypos": 2,
    "oxidationStates": [
      -3,
      -2,
      -1,
      1,
      2,
      3,
      4,
      5
    ],
    "electronegativity": 3.04
  },
  {
    "z": 8,
    "symbol": "O",
    "name": "Oxygen",
    "mass": 15.999,
    "category": "nonmetal",
    "period": 2,
    "group": 16,
    "xpos": 16,
    "ypos": 2,
    "oxidationStates": [
      -2,
      -1,
      1,
      2
    ],
    "electronegativity": 3.44
  },
  {
    "z": 9,
    "symbol": "F",
    "name": "Fluorine",
    "mass": 18.998,
    "category": "halogen",
    "period": 2,
    "group": 17,
    "xpos": 17,
    "ypos": 2,
    "oxidationStates": [
      -1
    ],
    "electronegativity": 3.98
  },
  {
    "z": 10,
    "symbol": "Ne",
    "name": "Neon",
    "mass": 20.18,
    "category": "noble-gas",
    "period": 2,
    "group": 18,
    "xpos": 18,
    "ypos": 2,
    "oxidationStates": [
      0
    ],
    "electronegativity": null
  },
  {
    "z": 11,
    "symbol": "Na",
    "name": "Sodium",
    "mass": 22.99,
    "category": "alkali-metal",
    "period": 3,
    "group": 1,
    "xpos": 1,
    "ypos": 3,
    "oxidationStates": [
      1
    ],
    "electronegativity": 0.93
  },
  {
    "z": 12,
    "symbol": "Mg",
    "name": "Magnesium",
    "mass": 24.305,
    "category": "alkaline-earth",
    "period": 3,
    "group": 2,
    "xpos": 2,
    "ypos": 3,
    "oxidationStates": [
      2
    ],
    "electronegativity": 1.31
  },
  {
    "z": 13,
    "symbol": "Al",
    "name": "Aluminium",
    "mass": 26.982,
    "category": "post-transition",
    "period": 3,
    "group": 13,
    "xpos": 13,
    "ypos": 3,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.61
  },
  {
    "z": 14,
    "symbol": "Si",
    "name": "Silicon",
    "mass": 28.085,
    "category": "metalloid",
    "period": 3,
    "group": 14,
    "xpos": 14,
    "ypos": 3,
    "oxidationStates": [
      -4,
      4
    ],
    "electronegativity": 1.9
  },
  {
    "z": 15,
    "symbol": "P",
    "name": "Phosphorus",
    "mass": 30.974,
    "category": "nonmetal",
    "period": 3,
    "group": 15,
    "xpos": 15,
    "ypos": 3,
    "oxidationStates": [
      -3,
      3,
      5
    ],
    "electronegativity": 2.19
  },
  {
    "z": 16,
    "symbol": "S",
    "name": "Sulfur",
    "mass": 32.06,
    "category": "nonmetal",
    "period": 3,
    "group": 16,
    "xpos": 16,
    "ypos": 3,
    "oxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "electronegativity": 2.58
  },
  {
    "z": 17,
    "symbol": "Cl",
    "name": "Chlorine",
    "mass": 35.45,
    "category": "halogen",
    "period": 3,
    "group": 17,
    "xpos": 17,
    "ypos": 3,
    "oxidationStates": [
      -1,
      1,
      3,
      5,
      7
    ],
    "electronegativity": 3.16
  },
  {
    "z": 18,
    "symbol": "Ar",
    "name": "Argon",
    "mass": 39.948,
    "category": "noble-gas",
    "period": 3,
    "group": 18,
    "xpos": 18,
    "ypos": 3,
    "oxidationStates": [
      0
    ],
    "electronegativity": null
  },
  {
    "z": 19,
    "symbol": "K",
    "name": "Potassium",
    "mass": 39.098,
    "category": "alkali-metal",
    "period": 4,
    "group": 1,
    "xpos": 1,
    "ypos": 4,
    "oxidationStates": [
      1
    ],
    "electronegativity": 0.82
  },
  {
    "z": 20,
    "symbol": "Ca",
    "name": "Calcium",
    "mass": 40.078,
    "category": "alkaline-earth",
    "period": 4,
    "group": 2,
    "xpos": 2,
    "ypos": 4,
    "oxidationStates": [
      2
    ],
    "electronegativity": 1
  },
  {
    "z": 21,
    "symbol": "Sc",
    "name": "Scandium",
    "mass": 44.956,
    "category": "transition-metal",
    "period": 4,
    "group": 3,
    "xpos": 3,
    "ypos": 4,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.36
  },
  {
    "z": 22,
    "symbol": "Ti",
    "name": "Titanium",
    "mass": 47.867,
    "category": "transition-metal",
    "period": 4,
    "group": 4,
    "xpos": 4,
    "ypos": 4,
    "oxidationStates": [
      2,
      3,
      4
    ],
    "electronegativity": 1.54
  },
  {
    "z": 23,
    "symbol": "V",
    "name": "Vanadium",
    "mass": 50.942,
    "category": "transition-metal",
    "period": 4,
    "group": 5,
    "xpos": 5,
    "ypos": 4,
    "oxidationStates": [
      2,
      3,
      4,
      5
    ],
    "electronegativity": 1.63
  },
  {
    "z": 24,
    "symbol": "Cr",
    "name": "Chromium",
    "mass": 51.996,
    "category": "transition-metal",
    "period": 4,
    "group": 6,
    "xpos": 6,
    "ypos": 4,
    "oxidationStates": [
      2,
      3,
      6
    ],
    "electronegativity": 1.66
  },
  {
    "z": 25,
    "symbol": "Mn",
    "name": "Manganese",
    "mass": 54.938,
    "category": "transition-metal",
    "period": 4,
    "group": 7,
    "xpos": 7,
    "ypos": 4,
    "oxidationStates": [
      2,
      3,
      4,
      6,
      7
    ],
    "electronegativity": 1.55
  },
  {
    "z": 26,
    "symbol": "Fe",
    "name": "Iron",
    "mass": 55.845,
    "category": "transition-metal",
    "period": 4,
    "group": 8,
    "xpos": 8,
    "ypos": 4,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": 1.83
  },
  {
    "z": 27,
    "symbol": "Co",
    "name": "Cobalt",
    "mass": 58.933,
    "category": "transition-metal",
    "period": 4,
    "group": 9,
    "xpos": 9,
    "ypos": 4,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": 1.88
  },
  {
    "z": 28,
    "symbol": "Ni",
    "name": "Nickel",
    "mass": 58.693,
    "category": "transition-metal",
    "period": 4,
    "group": 10,
    "xpos": 10,
    "ypos": 4,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": 1.91
  },
  {
    "z": 29,
    "symbol": "Cu",
    "name": "Copper",
    "mass": 63.546,
    "category": "transition-metal",
    "period": 4,
    "group": 11,
    "xpos": 11,
    "ypos": 4,
    "oxidationStates": [
      1,
      2
    ],
    "electronegativity": 1.9
  },
  {
    "z": 30,
    "symbol": "Zn",
    "name": "Zinc",
    "mass": 65.38,
    "category": "transition-metal",
    "period": 4,
    "group": 12,
    "xpos": 12,
    "ypos": 4,
    "oxidationStates": [
      2
    ],
    "electronegativity": 1.65
  },
  {
    "z": 31,
    "symbol": "Ga",
    "name": "Gallium",
    "mass": 69.723,
    "category": "post-transition",
    "period": 4,
    "group": 13,
    "xpos": 13,
    "ypos": 4,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.81
  },
  {
    "z": 32,
    "symbol": "Ge",
    "name": "Germanium",
    "mass": 72.63,
    "category": "metalloid",
    "period": 4,
    "group": 14,
    "xpos": 14,
    "ypos": 4,
    "oxidationStates": [
      -4,
      2,
      4
    ],
    "electronegativity": 2.01
  },
  {
    "z": 33,
    "symbol": "As",
    "name": "Arsenic",
    "mass": 74.922,
    "category": "metalloid",
    "period": 4,
    "group": 15,
    "xpos": 15,
    "ypos": 4,
    "oxidationStates": [
      -3,
      3,
      5
    ],
    "electronegativity": 2.18
  },
  {
    "z": 34,
    "symbol": "Se",
    "name": "Selenium",
    "mass": 78.971,
    "category": "nonmetal",
    "period": 4,
    "group": 16,
    "xpos": 16,
    "ypos": 4,
    "oxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "electronegativity": 2.55
  },
  {
    "z": 35,
    "symbol": "Br",
    "name": "Bromine",
    "mass": 79.904,
    "category": "halogen",
    "period": 4,
    "group": 17,
    "xpos": 17,
    "ypos": 4,
    "oxidationStates": [
      -1,
      1,
      3,
      5
    ],
    "electronegativity": 2.96
  },
  {
    "z": 36,
    "symbol": "Kr",
    "name": "Krypton",
    "mass": 83.798,
    "category": "noble-gas",
    "period": 4,
    "group": 18,
    "xpos": 18,
    "ypos": 4,
    "oxidationStates": [
      0,
      2
    ],
    "electronegativity": 3
  },
  {
    "z": 37,
    "symbol": "Rb",
    "name": "Rubidium",
    "mass": 85.468,
    "category": "alkali-metal",
    "period": 5,
    "group": 1,
    "xpos": 1,
    "ypos": 5,
    "oxidationStates": [
      1
    ],
    "electronegativity": 0.82
  },
  {
    "z": 38,
    "symbol": "Sr",
    "name": "Strontium",
    "mass": 87.62,
    "category": "alkaline-earth",
    "period": 5,
    "group": 2,
    "xpos": 2,
    "ypos": 5,
    "oxidationStates": [
      2
    ],
    "electronegativity": 0.95
  },
  {
    "z": 39,
    "symbol": "Y",
    "name": "Yttrium",
    "mass": 88.906,
    "category": "transition-metal",
    "period": 5,
    "group": 3,
    "xpos": 3,
    "ypos": 5,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.22
  },
  {
    "z": 40,
    "symbol": "Zr",
    "name": "Zirconium",
    "mass": 91.224,
    "category": "transition-metal",
    "period": 5,
    "group": 4,
    "xpos": 4,
    "ypos": 5,
    "oxidationStates": [
      4
    ],
    "electronegativity": 1.33
  },
  {
    "z": 41,
    "symbol": "Nb",
    "name": "Niobium",
    "mass": 92.906,
    "category": "transition-metal",
    "period": 5,
    "group": 5,
    "xpos": 5,
    "ypos": 5,
    "oxidationStates": [
      3,
      5
    ],
    "electronegativity": 1.6
  },
  {
    "z": 42,
    "symbol": "Mo",
    "name": "Molybdenum",
    "mass": 95.95,
    "category": "transition-metal",
    "period": 5,
    "group": 6,
    "xpos": 6,
    "ypos": 5,
    "oxidationStates": [
      2,
      3,
      4,
      5,
      6
    ],
    "electronegativity": 2.16
  },
  {
    "z": 43,
    "symbol": "Tc",
    "name": "Technetium",
    "mass": 98,
    "category": "transition-metal",
    "period": 5,
    "group": 7,
    "xpos": 7,
    "ypos": 5,
    "oxidationStates": [
      4,
      7
    ],
    "electronegativity": 1.9
  },
  {
    "z": 44,
    "symbol": "Ru",
    "name": "Ruthenium",
    "mass": 101.07,
    "category": "transition-metal",
    "period": 5,
    "group": 8,
    "xpos": 8,
    "ypos": 5,
    "oxidationStates": [
      2,
      3,
      4,
      6,
      8
    ],
    "electronegativity": 2.2
  },
  {
    "z": 45,
    "symbol": "Rh",
    "name": "Rhodium",
    "mass": 102.91,
    "category": "transition-metal",
    "period": 5,
    "group": 9,
    "xpos": 9,
    "ypos": 5,
    "oxidationStates": [
      3
    ],
    "electronegativity": 2.28
  },
  {
    "z": 46,
    "symbol": "Pd",
    "name": "Palladium",
    "mass": 106.42,
    "category": "transition-metal",
    "period": 5,
    "group": 10,
    "xpos": 10,
    "ypos": 5,
    "oxidationStates": [
      2,
      4
    ],
    "electronegativity": 2.2
  },
  {
    "z": 47,
    "symbol": "Ag",
    "name": "Silver",
    "mass": 107.87,
    "category": "transition-metal",
    "period": 5,
    "group": 11,
    "xpos": 11,
    "ypos": 5,
    "oxidationStates": [
      1
    ],
    "electronegativity": 1.93
  },
  {
    "z": 48,
    "symbol": "Cd",
    "name": "Cadmium",
    "mass": 112.41,
    "category": "transition-metal",
    "period": 5,
    "group": 12,
    "xpos": 12,
    "ypos": 5,
    "oxidationStates": [
      2
    ],
    "electronegativity": 1.69
  },
  {
    "z": 49,
    "symbol": "In",
    "name": "Indium",
    "mass": 114.82,
    "category": "post-transition",
    "period": 5,
    "group": 13,
    "xpos": 13,
    "ypos": 5,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.78
  },
  {
    "z": 50,
    "symbol": "Sn",
    "name": "Tin",
    "mass": 118.71,
    "category": "post-transition",
    "period": 5,
    "group": 14,
    "xpos": 14,
    "ypos": 5,
    "oxidationStates": [
      -4,
      2,
      4
    ],
    "electronegativity": 1.96
  },
  {
    "z": 51,
    "symbol": "Sb",
    "name": "Antimony",
    "mass": 121.76,
    "category": "metalloid",
    "period": 5,
    "group": 15,
    "xpos": 15,
    "ypos": 5,
    "oxidationStates": [
      -3,
      3,
      5
    ],
    "electronegativity": 2.05
  },
  {
    "z": 52,
    "symbol": "Te",
    "name": "Tellurium",
    "mass": 127.6,
    "category": "metalloid",
    "period": 5,
    "group": 16,
    "xpos": 16,
    "ypos": 5,
    "oxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "electronegativity": 2.1
  },
  {
    "z": 53,
    "symbol": "I",
    "name": "Iodine",
    "mass": 126.9,
    "category": "halogen",
    "period": 5,
    "group": 17,
    "xpos": 17,
    "ypos": 5,
    "oxidationStates": [
      -1,
      1,
      3,
      5,
      7
    ],
    "electronegativity": 2.66
  },
  {
    "z": 54,
    "symbol": "Xe",
    "name": "Xenon",
    "mass": 131.29,
    "category": "noble-gas",
    "period": 5,
    "group": 18,
    "xpos": 18,
    "ypos": 5,
    "oxidationStates": [
      0,
      2,
      4,
      6,
      8
    ],
    "electronegativity": 2.6
  },
  {
    "z": 55,
    "symbol": "Cs",
    "name": "Caesium",
    "mass": 132.91,
    "category": "alkali-metal",
    "period": 6,
    "group": 1,
    "xpos": 1,
    "ypos": 6,
    "oxidationStates": [
      1
    ],
    "electronegativity": 0.79
  },
  {
    "z": 56,
    "symbol": "Ba",
    "name": "Barium",
    "mass": 137.33,
    "category": "alkaline-earth",
    "period": 6,
    "group": 2,
    "xpos": 2,
    "ypos": 6,
    "oxidationStates": [
      2
    ],
    "electronegativity": 0.89
  },
  {
    "z": 57,
    "symbol": "La",
    "name": "Lanthanum",
    "mass": 138.91,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 3,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.1
  },
  {
    "z": 58,
    "symbol": "Ce",
    "name": "Cerium",
    "mass": 140.12,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 4,
    "ypos": 9,
    "oxidationStates": [
      3,
      4
    ],
    "electronegativity": 1.12
  },
  {
    "z": 59,
    "symbol": "Pr",
    "name": "Praseodymium",
    "mass": 140.91,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 5,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.13
  },
  {
    "z": 60,
    "symbol": "Nd",
    "name": "Neodymium",
    "mass": 144.24,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 6,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.14
  },
  {
    "z": 61,
    "symbol": "Pm",
    "name": "Promethium",
    "mass": 145,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 7,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": null
  },
  {
    "z": 62,
    "symbol": "Sm",
    "name": "Samarium",
    "mass": 150.36,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 8,
    "ypos": 9,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": 1.17
  },
  {
    "z": 63,
    "symbol": "Eu",
    "name": "Europium",
    "mass": 151.96,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 9,
    "ypos": 9,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": null
  },
  {
    "z": 64,
    "symbol": "Gd",
    "name": "Gadolinium",
    "mass": 157.25,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 10,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.2
  },
  {
    "z": 65,
    "symbol": "Tb",
    "name": "Terbium",
    "mass": 158.93,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 11,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": null
  },
  {
    "z": 66,
    "symbol": "Dy",
    "name": "Dysprosium",
    "mass": 162.5,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 12,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.22
  },
  {
    "z": 67,
    "symbol": "Ho",
    "name": "Holmium",
    "mass": 164.93,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 13,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.23
  },
  {
    "z": 68,
    "symbol": "Er",
    "name": "Erbium",
    "mass": 167.26,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 14,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.24
  },
  {
    "z": 69,
    "symbol": "Tm",
    "name": "Thulium",
    "mass": 168.93,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 15,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.25
  },
  {
    "z": 70,
    "symbol": "Yb",
    "name": "Ytterbium",
    "mass": 173.05,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 16,
    "ypos": 9,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": null
  },
  {
    "z": 71,
    "symbol": "Lu",
    "name": "Lutetium",
    "mass": 174.97,
    "category": "lanthanide",
    "period": 6,
    "group": 3,
    "xpos": 17,
    "ypos": 9,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.27
  },
  {
    "z": 72,
    "symbol": "Hf",
    "name": "Hafnium",
    "mass": 178.49,
    "category": "transition-metal",
    "period": 6,
    "group": 4,
    "xpos": 4,
    "ypos": 6,
    "oxidationStates": [
      4
    ],
    "electronegativity": 1.3
  },
  {
    "z": 73,
    "symbol": "Ta",
    "name": "Tantalum",
    "mass": 180.95,
    "category": "transition-metal",
    "period": 6,
    "group": 5,
    "xpos": 5,
    "ypos": 6,
    "oxidationStates": [
      5
    ],
    "electronegativity": 1.5
  },
  {
    "z": 74,
    "symbol": "W",
    "name": "Tungsten",
    "mass": 183.84,
    "category": "transition-metal",
    "period": 6,
    "group": 6,
    "xpos": 6,
    "ypos": 6,
    "oxidationStates": [
      2,
      3,
      4,
      5,
      6
    ],
    "electronegativity": 2.36
  },
  {
    "z": 75,
    "symbol": "Re",
    "name": "Rhenium",
    "mass": 186.21,
    "category": "transition-metal",
    "period": 6,
    "group": 7,
    "xpos": 7,
    "ypos": 6,
    "oxidationStates": [
      4,
      7
    ],
    "electronegativity": 1.9
  },
  {
    "z": 76,
    "symbol": "Os",
    "name": "Osmium",
    "mass": 190.23,
    "category": "transition-metal",
    "period": 6,
    "group": 8,
    "xpos": 8,
    "ypos": 6,
    "oxidationStates": [
      3,
      4,
      6,
      8
    ],
    "electronegativity": 2.2
  },
  {
    "z": 77,
    "symbol": "Ir",
    "name": "Iridium",
    "mass": 192.22,
    "category": "transition-metal",
    "period": 6,
    "group": 9,
    "xpos": 9,
    "ypos": 6,
    "oxidationStates": [
      3,
      4
    ],
    "electronegativity": 2.2
  },
  {
    "z": 78,
    "symbol": "Pt",
    "name": "Platinum",
    "mass": 195.08,
    "category": "transition-metal",
    "period": 6,
    "group": 10,
    "xpos": 10,
    "ypos": 6,
    "oxidationStates": [
      2,
      4
    ],
    "electronegativity": 2.28
  },
  {
    "z": 79,
    "symbol": "Au",
    "name": "Gold",
    "mass": 196.97,
    "category": "transition-metal",
    "period": 6,
    "group": 11,
    "xpos": 11,
    "ypos": 6,
    "oxidationStates": [
      1,
      3
    ],
    "electronegativity": 2.54
  },
  {
    "z": 80,
    "symbol": "Hg",
    "name": "Mercury",
    "mass": 200.59,
    "category": "transition-metal",
    "period": 6,
    "group": 12,
    "xpos": 12,
    "ypos": 6,
    "oxidationStates": [
      1,
      2
    ],
    "electronegativity": 2
  },
  {
    "z": 81,
    "symbol": "Tl",
    "name": "Thallium",
    "mass": 204.38,
    "category": "post-transition",
    "period": 6,
    "group": 13,
    "xpos": 13,
    "ypos": 6,
    "oxidationStates": [
      1,
      3
    ],
    "electronegativity": 1.62
  },
  {
    "z": 82,
    "symbol": "Pb",
    "name": "Lead",
    "mass": 207.2,
    "category": "post-transition",
    "period": 6,
    "group": 14,
    "xpos": 14,
    "ypos": 6,
    "oxidationStates": [
      2,
      4
    ],
    "electronegativity": 2.33
  },
  {
    "z": 83,
    "symbol": "Bi",
    "name": "Bismuth",
    "mass": 208.98,
    "category": "post-transition",
    "period": 6,
    "group": 15,
    "xpos": 15,
    "ypos": 6,
    "oxidationStates": [
      3,
      5
    ],
    "electronegativity": 2.02
  },
  {
    "z": 84,
    "symbol": "Po",
    "name": "Polonium",
    "mass": 209,
    "category": "post-transition",
    "period": 6,
    "group": 16,
    "xpos": 16,
    "ypos": 6,
    "oxidationStates": [
      -2,
      2,
      4,
      6
    ],
    "electronegativity": 2
  },
  {
    "z": 85,
    "symbol": "At",
    "name": "Astatine",
    "mass": 210,
    "category": "halogen",
    "period": 6,
    "group": 17,
    "xpos": 17,
    "ypos": 6,
    "oxidationStates": [
      -1,
      1
    ],
    "electronegativity": 2.2
  },
  {
    "z": 86,
    "symbol": "Rn",
    "name": "Radon",
    "mass": 222,
    "category": "noble-gas",
    "period": 6,
    "group": 18,
    "xpos": 18,
    "ypos": 6,
    "oxidationStates": [
      0,
      2
    ],
    "electronegativity": null
  },
  {
    "z": 87,
    "symbol": "Fr",
    "name": "Francium",
    "mass": 223,
    "category": "alkali-metal",
    "period": 7,
    "group": 1,
    "xpos": 1,
    "ypos": 7,
    "oxidationStates": [
      1
    ],
    "electronegativity": null
  },
  {
    "z": 88,
    "symbol": "Ra",
    "name": "Radium",
    "mass": 226,
    "category": "alkaline-earth",
    "period": 7,
    "group": 2,
    "xpos": 2,
    "ypos": 7,
    "oxidationStates": [
      2
    ],
    "electronegativity": 0.9
  },
  {
    "z": 89,
    "symbol": "Ac",
    "name": "Actinium",
    "mass": 227,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 3,
    "ypos": 10,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.1
  },
  {
    "z": 90,
    "symbol": "Th",
    "name": "Thorium",
    "mass": 232.04,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 4,
    "ypos": 10,
    "oxidationStates": [
      4
    ],
    "electronegativity": 1.3
  },
  {
    "z": 91,
    "symbol": "Pa",
    "name": "Protactinium",
    "mass": 231.04,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 5,
    "ypos": 10,
    "oxidationStates": [
      4,
      5
    ],
    "electronegativity": 1.5
  },
  {
    "z": 92,
    "symbol": "U",
    "name": "Uranium",
    "mass": 238.03,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 6,
    "ypos": 10,
    "oxidationStates": [
      3,
      4,
      5,
      6
    ],
    "electronegativity": 1.38
  },
  {
    "z": 93,
    "symbol": "Np",
    "name": "Neptunium",
    "mass": 237,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 7,
    "ypos": 10,
    "oxidationStates": [
      3,
      4,
      5,
      6,
      7
    ],
    "electronegativity": 1.36
  },
  {
    "z": 94,
    "symbol": "Pu",
    "name": "Plutonium",
    "mass": 244,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 8,
    "ypos": 10,
    "oxidationStates": [
      3,
      4,
      5,
      6
    ],
    "electronegativity": 1.28
  },
  {
    "z": 95,
    "symbol": "Am",
    "name": "Americium",
    "mass": 243,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 9,
    "ypos": 10,
    "oxidationStates": [
      3,
      4,
      5,
      6
    ],
    "electronegativity": 1.3
  },
  {
    "z": 96,
    "symbol": "Cm",
    "name": "Curium",
    "mass": 247,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 10,
    "ypos": 10,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.3
  },
  {
    "z": 97,
    "symbol": "Bk",
    "name": "Berkelium",
    "mass": 247,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 11,
    "ypos": 10,
    "oxidationStates": [
      3,
      4
    ],
    "electronegativity": 1.3
  },
  {
    "z": 98,
    "symbol": "Cf",
    "name": "Californium",
    "mass": 251,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 12,
    "ypos": 10,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.3
  },
  {
    "z": 99,
    "symbol": "Es",
    "name": "Einsteinium",
    "mass": 252,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 13,
    "ypos": 10,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.3
  },
  {
    "z": 100,
    "symbol": "Fm",
    "name": "Fermium",
    "mass": 257,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 14,
    "ypos": 10,
    "oxidationStates": [
      3
    ],
    "electronegativity": 1.3
  },
  {
    "z": 101,
    "symbol": "Md",
    "name": "Mendelevium",
    "mass": 258,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 15,
    "ypos": 10,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": 1.3
  },
  {
    "z": 102,
    "symbol": "No",
    "name": "Nobelium",
    "mass": 259,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 16,
    "ypos": 10,
    "oxidationStates": [
      2,
      3
    ],
    "electronegativity": 1.3
  },
  {
    "z": 103,
    "symbol": "Lr",
    "name": "Lawrencium",
    "mass": 266,
    "category": "actinide",
    "period": 7,
    "group": 3,
    "xpos": 17,
    "ypos": 10,
    "oxidationStates": [
      3
    ],
    "electronegativity": null
  },
  {
    "z": 104,
    "symbol": "Rf",
    "name": "Rutherfordium",
    "mass": 267,
    "category": "transition-metal",
    "period": 7,
    "group": 4,
    "xpos": 4,
    "ypos": 7,
    "oxidationStates": [
      4
    ],
    "electronegativity": null
  },
  {
    "z": 105,
    "symbol": "Db",
    "name": "Dubnium",
    "mass": 268,
    "category": "transition-metal",
    "period": 7,
    "group": 5,
    "xpos": 5,
    "ypos": 7,
    "oxidationStates": [
      5
    ],
    "electronegativity": null
  },
  {
    "z": 106,
    "symbol": "Sg",
    "name": "Seaborgium",
    "mass": 269,
    "category": "transition-metal",
    "period": 7,
    "group": 6,
    "xpos": 6,
    "ypos": 7,
    "oxidationStates": [
      6
    ],
    "electronegativity": null
  },
  {
    "z": 107,
    "symbol": "Bh",
    "name": "Bohrium",
    "mass": 270,
    "category": "transition-metal",
    "period": 7,
    "group": 7,
    "xpos": 7,
    "ypos": 7,
    "oxidationStates": [
      7
    ],
    "electronegativity": null
  },
  {
    "z": 108,
    "symbol": "Hs",
    "name": "Hassium",
    "mass": 269,
    "category": "transition-metal",
    "period": 7,
    "group": 8,
    "xpos": 8,
    "ypos": 7,
    "oxidationStates": [
      8
    ],
    "electronegativity": null
  },
  {
    "z": 109,
    "symbol": "Mt",
    "name": "Meitnerium",
    "mass": 278,
    "category": "unknown",
    "period": 7,
    "group": 9,
    "xpos": 9,
    "ypos": 7,
    "oxidationStates": [],
    "electronegativity": null
  },
  {
    "z": 110,
    "symbol": "Ds",
    "name": "Darmstadtium",
    "mass": 281,
    "category": "unknown",
    "period": 7,
    "group": 10,
    "xpos": 10,
    "ypos": 7,
    "oxidationStates": [],
    "electronegativity": null
  },
  {
    "z": 111,
    "symbol": "Rg",
    "name": "Roentgenium",
    "mass": 282,
    "category": "unknown",
    "period": 7,
    "group": 11,
    "xpos": 11,
    "ypos": 7,
    "oxidationStates": [],
    "electronegativity": null
  },
  {
    "z": 112,
    "symbol": "Cn",
    "name": "Copernicium",
    "mass": 285,
    "category": "unknown",
    "period": 7,
    "group": 12,
    "xpos": 12,
    "ypos": 7,
    "oxidationStates": [
      2
    ],
    "electronegativity": null
  },
  {
    "z": 113,
    "symbol": "Nh",
    "name": "Nihonium",
    "mass": 286,
    "category": "unknown",
    "period": 7,
    "group": 13,
    "xpos": 13,
    "ypos": 7,
    "oxidationStates": [
      1
    ],
    "electronegativity": null
  },
  {
    "z": 114,
    "symbol": "Fl",
    "name": "Flerovium",
    "mass": 289,
    "category": "unknown",
    "period": 7,
    "group": 14,
    "xpos": 14,
    "ypos": 7,
    "oxidationStates": [
      2
    ],
    "electronegativity": null
  },
  {
    "z": 115,
    "symbol": "Mc",
    "name": "Moscovium",
    "mass": 290,
    "category": "unknown",
    "period": 7,
    "group": 15,
    "xpos": 15,
    "ypos": 7,
    "oxidationStates": [
      1
    ],
    "electronegativity": null
  },
  {
    "z": 116,
    "symbol": "Lv",
    "name": "Livermorium",
    "mass": 293,
    "category": "unknown",
    "period": 7,
    "group": 16,
    "xpos": 16,
    "ypos": 7,
    "oxidationStates": [
      2
    ],
    "electronegativity": null
  },
  {
    "z": 117,
    "symbol": "Ts",
    "name": "Tennessine",
    "mass": 294,
    "category": "unknown",
    "period": 7,
    "group": 17,
    "xpos": 17,
    "ypos": 7,
    "oxidationStates": [
      -1,
      1
    ],
    "electronegativity": null
  },
  {
    "z": 118,
    "symbol": "Og",
    "name": "Oganesson",
    "mass": 294,
    "category": "noble-gas",
    "period": 7,
    "group": 18,
    "xpos": 18,
    "ypos": 7,
    "oxidationStates": [
      0
    ],
    "electronegativity": null
  }
];

export const BY_SYMBOL: Record<string, ElementDef> = Object.fromEntries(
  ELEMENTS.map((e) => [e.symbol, e]),
);

export function elementsInPeriod(p: number): ElementDef[] {
  return ELEMENTS.filter((e) => e.period === p && e.category !== "lanthanide" && e.category !== "actinide")
    .concat(ELEMENTS.filter((e) => (p === 6 && e.category === "lanthanide") || (p === 7 && e.category === "actinide")));
}
